// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFXsoEx0kxRS-rmiFsTskV1hiYrphJHhQ',
    appId: '1:558607615805:web:9c03c375594a5da1762754',
    messagingSenderId: '558607615805',
    projectId: 'social-app-a1a66',
    authDomain: 'social-app-a1a66.firebaseapp.com',
    storageBucket: 'social-app-a1a66.appspot.com',
    measurementId: 'G-CY5553FV1T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbxlSscXeWiSkvIxygvjK_zbDX-8TiCn4',
    appId: '1:558607615805:android:a93b3fb20535c8f2762754',
    messagingSenderId: '558607615805',
    projectId: 'social-app-a1a66',
    storageBucket: 'social-app-a1a66.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR6LYHi9e0BxSOJzQpPaMMsFvBn5Vzll8',
    appId: '1:558607615805:ios:4a148e472c772f5e762754',
    messagingSenderId: '558607615805',
    projectId: 'social-app-a1a66',
    storageBucket: 'social-app-a1a66.appspot.com',
    iosClientId: '558607615805-affdqjjvkqdp4t4gjdd492nbko0psb68.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCR6LYHi9e0BxSOJzQpPaMMsFvBn5Vzll8',
    appId: '1:558607615805:ios:4a148e472c772f5e762754',
    messagingSenderId: '558607615805',
    projectId: 'social-app-a1a66',
    storageBucket: 'social-app-a1a66.appspot.com',
    iosClientId: '558607615805-affdqjjvkqdp4t4gjdd492nbko0psb68.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialApp',
  );
}
